import 'tailwindcss/tailwind.css';
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar/NavBar';
import { Providers } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ElectroShop',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <NavBar />
        </header>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
